### ISSUE TITLE
TouchTracking adding same ID

### ISSUE THREAD

**Issue by GregaMohorko** [Cheesebaron/SkiaScene#1] opened 2018-02-23 12:56 UTC
TouchTracking works beautifully on Android, but not on iOS.

On Android, the Id of the TouchActionEventArgs always starts with zero. On iOS, it is a random very big number.
However, this is not such a big deal. But! After experimenting a little and clicking fast... an ArgumentException is thrown. Happened three times already now.
And I guess the root of the problem is the Id, because it tries to add the same Id as was the last Id. Check the output below.

**Output:**
*Format: [Id] Type: (x,y), IsInContact*

[0:] [412542000] Pressed: (91,35715,90,71429), True
[0:] [412542000] Moved: (89,85715,83,21429), True
[0:] [412542000] Moved: (87,85715,80,21429), True
[0:] [412594224] Pressed: (80,85715,105,7143), True
[0:] [412594224] Moved: (74,85715,96,21429), True
[0:] [412594224] Moved: (74,85715,93,71429), True
[0:] [412474624] Pressed: (64,35715,95,21429), True
Unhandled Exception:

System.ArgumentException: An item with the same key has already been added. Key: 412474624

**Stacktrace:**

>   at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000b1] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.4/src/mono/external/corert/src/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs:411

>   at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.4/src/mono/external/corert/src/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs:234

>   at TouchTracking.iOS.TouchRecognizer.TouchesBegan (Foundation.NSSet touches, UIKit.UIEvent evt) [0x00037] in <bfcae84600564bf3b0a6af9db959835d>:0

**Comment by OndrejKunc** [comment] 2018-02-26 09:16
Hey Grega, thanks for reporting this issue. 
Unfortunately I am not able to reproduce it. Based on your output and stacktrace, it looks like TouchRecognizer object doesn't detect end of your gesture. This object has static dictionary, which tracks all your fingers - it adds Id of each finger on TouchesBegan method from UIGestureRecognizer base class and remove the id on method TouchesEnded or TouchesCancelled. However, since I can see only Pressed and Moved events in your log and no Released, I assume that those methods are never called and so you eventually run into a situation, when it attempts to add same key again.

I suppose your issue may be simmilar to the issue in this post https://stackoverflow.com/questions/22127451/touches-ended-not-being-called
According to this post, fix may be to simply set CancelsTouchesInView flag to false. But to be sure, I would like to verify it first and will need some details from you.

1, Do you ever see TouchActionType.Released in your log?
2. Are you able to reproduce it on sample SkiaScene.FormsSample.iOS in this repository?
3. Are you using device or simulator? Which type of device and simulator?
4. Does it happen when you use multiple fingers or just one finger?
5. How does your view looks like? Is your control on fullscreen? Do you have any other gesture recognizers attached to this control?

If you couldn't reproduce it on SkiaScene.FormsSample.iOS, it would be great if you could provide some example.

Thanks

**Comment by GregaMohorko** [comment] 2018-02-26 15:06
Hey Ondrej, thanks for replying.

Currently I'm not at the office so I can't try anything, but when I will, I will report back here.

To answer your questions:
1. Yes, Released is seen only when I quickly tap so that there is no Moved event. Only Pressed, and then Released.
2. I haven't tried any of the sample repositories, but I will.
3. I'm using a device, an iPhone 5s with iOS 10.2.
4. I was always testing just with the one finger.
5. My control is inside a `ScrollView`, which is inside a `ContentPage`, which is a Detail page of a `MasterDetailPage`. And here I think is the main problem: when I press and then move, the movement is captured either by the `ScrollView` _(vertical movement)_ or by the `MasterDetailPage` _(horizontal movement, trying to show the Master page)_.

**Comment by OndrejKunc** [comment] 2018-03-02 16:24
Thanks for the answers. You are proprably right, the problem is in your specific layout. 
I tried to put the skia control inside ScrollView in sample project and I stopped receiving released events as well.

Unfortunatelly I am afraid I cannot solve this from the library, since this event is never received and only solution I can think of is to update your layout accordingly. This is probably simmilar issue like having ListView inside ScrollView, which is not recommended thing to do, because of the scrolling conflicts. Another solution may be to write your custom native renderer for ScrollView and set CancelsTouchesInView flag which I mentioned, which may allow child controls to recieve all touch events.

If I am wrong and you find a way how to solve this from the library, please let me know or feel free to make pull request :)

**Closed as completed** 2018-03-22 16:28 UTC

**Comment by balazserd** [comment] 2019-06-01 06:43
@GregaMohorko Can you please share how you solved the issue? I am facing the very same one.

**Comment by GregaMohorko** [comment] 2019-06-02 21:40
@balazserd I haven't solved it, I simply don-t use this library in iOS. Sorry.

**Comment by robertvo** [comment] 2021-03-19 14:50
three years later I'm having the same issue :(
